### Name: Birehan Anteneh
### ID N0: UGR/4886/12

# PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course.
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch

import torch
# Create random tensor
random_tensor = torch.rand(7, 7)
print(random_tensor)

tensor([[0.3616, 0.3513, 0.6106, 0.2258, 0.7427, 0.4757, 0.3251],
        [0.1393, 0.1666, 0.5646, 0.3167, 0.1018, 0.2310, 0.6372],
        [0.3134, 0.3081, 0.5985, 0.2161, 0.9012, 0.9734, 0.5766],
        [0.1371, 0.4617, 0.1895, 0.2862, 0.8829, 0.0777, 0.4160],
        [0.5741, 0.1826, 0.8660, 0.1289, 0.3663, 0.0550, 0.7405],
        [0.7777, 0.3321, 0.1280, 0.7695, 0.5877, 0.1115, 0.2055],
        [0.7058, 0.6106, 0.8020, 0.8430, 0.7635, 0.0905, 0.3246]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
random_tensor2 = torch.rand(1, 7)
random_tensor2_transposed = random_tensor2.t()

# Perform matrix multiplication
result = torch.mm(random_tensor, random_tensor2_transposed)

print(result)


tensor([[1.7088],
        [1.1622],
        [2.3099],
        [1.0916],
        [1.7021],
        [1.1885],
        [1.8187]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

> Indented block



The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [11]:
# Set manual seed

torch.manual_seed(0)

# Create two random tensors
random_tensor1 = torch.rand(7, 7)
random_tensor2 = torch.rand(1, 7)
random_tensor2_transposed = random_tensor2.t()
print(random_tensor1.shape, random_tensor2_transposed.shape)

# Matrix multiply tensors
result = torch.mm(random_tensor1, random_tensor2_transposed)
print(result)

torch.Size([7, 7]) torch.Size([7, 1])
tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [12]:
# Set random seed on the GPU
if torch.cuda.is_available():
  torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [13]:
# Set random seed

device = "cpu"

# if torch.cuda.is_available():
#     device = torch.device("cuda:0")

torch.manual_seed(1234)

# Create two random tensors
tensor1 = torch.rand(2, 3, device=device)
tensor2 = torch.rand(2, 3, device=device)

print("Device:", device)
print(tensor1)
print(tensor2)

Device: cpu
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [14]:
# Perform matmul on tensor_A and tensor_B
result = torch.mm(tensor1, tensor2.T)
print(result,result.device, result.size())

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]]) cpu torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

*   List item
*   List item



In [18]:
# Find max
max_value = torch.max(result)
# Find min
min_value = torch.min(result)


print("Maximum value:", max_value.item())
print("Minimum value:", min_value.item())

Maximum value: 0.5617256760597229
Minimum value: 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [25]:
print(result.argmax())

# Find arg max
max_indices = result.argmax()
# Find arg min
min_indices = result.argmin()
print("Indices of Maximum Value:", max_indices)
print("Indices of Minimum Value:", min_indices)

tensor(3)
Indices of Maximum Value: tensor(3)
Indices of Minimum Value: tensor(0)



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [26]:
# Set seed
torch.manual_seed(7)
# Create random tensor
tensor1 = torch.rand(1, 1, 1, 10)

# Remove single dimensions
tensor2 = tensor1.squeeze()

# Print out tensors and their shapes
print(tensor1)
print(tensor1.shape)
print(tensor2)
print(tensor2.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
torch.Size([10])
